feat: tweak dependency ensurance

diff --git a/libexec/commit b/libexec/commit
--- a/libexec/commit
+++ b/libexec/commit
@@ -3,10 +3,10 @@
 
 # Generate a report of the run, once it's completed
 
-command -v git &>/dev/null || {
-    echo 'Missing `git` -- cannot continue' >&2
-    exit 1
-}
+# shellcheck disable=2043
+for cmd in git; do
+    command -v "$cmd" &>/dev/null || echo "Missing $cmd -- cannot continue" >&2 && exit 1
+done
 
 . lib/vars
 
diff --git a/libexec/tag b/libexec/tag
--- a/libexec/tag
+++ b/libexec/tag
@@ -3,15 +3,9 @@
 
 # Generate a tag and release assets for the run, once it's completed
 
-command -v git &>/dev/null || {
-    echo 'Missing `git` -- cannot continue' >&2
-    exit 1
-}
-
-command -v gh &>/dev/null || {
-    echo 'Missing `gh` -- cannot continue' >&2
-    exit 1
-}
+for cmd in gh git; do
+    command -v "$cmd" &>/dev/null || echo "Missing $cmd -- cannot continue" >&2 && exit 1
+done
 
 . lib/vars
 
