feat: better behavior on empty versions

diff --git a/libexec/report b/libexec/report
--- a/libexec/report
+++ b/libexec/report
@@ -57,6 +57,22 @@ while read -r line; do
         l=$(echo "$line" | sed 's,-]{+,'$'\t',)
         l=$(echo "$l" | tr -d '+}[-')
         IFS=$'\t' read -r _ channel old new <<< "$l"
+
+        if [ -z "$old$new" ]; then
+            echo "WARNING: Missing old and new versions for $project:$channel" >&2
+            continue
+        fi
+
+        if [ -z "$old" ]; then
+            echo "WARNING: Missing old version for $project:$channel" >&2
+            continue
+        fi
+
+        if [ -z "$new" ]; then
+            echo "WARNING: Missing new version for $project:$channel" >&2
+            continue
+        fi
+
         printf "%-63s\t$(fmt $old) -> $(fmt $new)\n" "$project:$channel"
         continue
     fi
@@ -66,6 +82,12 @@ while read -r line; do
     if [[ $line == "{+"* ]]; then
         l=$(echo "$line" | tr -d '+}{')
         IFS=$'\t' read -r _ channel new <<< "$l"
+
+        if [ -z "$new" ]; then
+            echo "WARNING: Missing new version for $project:$channel" >&2
+            continue
+        fi
+
         printf "%-63s\t$(fmt $new)\n" "$project:$channel"
         continue
     fi
