feat: enable tagging

diff --git a/libexec/tag b/libexec/tag
--- a/libexec/tag
+++ b/libexec/tag
@@ -7,6 +7,11 @@ command -v git &>/dev/null || {
     exit 1
 }
 
+command -v gh &>/dev/null || {
+    echo 'Missing `gh` -- cannot continue' >&2
+    exit 1
+}
+
 . lib/vars
 
 shopt -s globstar
@@ -32,7 +37,7 @@ version="$(<version)"
     tar --numeric-owner --transform "s,p,p-$version-$runcount,"       -cJf "$VAT_TARGET/dist/p.tar.xz"    "p"
 )
 
-echo git tag "run-$runcount" -m "$(<$VAT_TARGET/report)"
-echo git push
-echo git push --tags
-echo gh release create "VAT $version run #$runcount" --notes-from-tag --latest=false "$VAT_TARGET/dist/"*
+git tag "run-$runcount" -m "$(<$VAT_TARGET/report)"
+git push
+git push --tags
+gh release create "VAT $version run #$runcount" --notes-from-tag --latest=false "$VAT_TARGET/dist/"*
