fix: send error messages to stderr

diff --git a/libexec/tag b/libexec/tag
--- a/libexec/tag
+++ b/libexec/tag
@@ -3,7 +3,7 @@
 # Generate a tag and release assets for the run, once it's completed
 
 command -v git &>/dev/null || {
-    echo 'Missing `git` -- cannot continue'
+    echo 'Missing `git` -- cannot continue' >&2
     exit 1
 }
 
